name: Deploy to prod

on:
  workflow_dispatch:
    inputs:
      version:
        description: "release number (e.g. 1)"
        required: true

env:
  IMAGE_BASE: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH → pull & run container
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: anuar
          key: ${{ secrets.SSH_KEY }}
          script: |
            # получаем токен из метаданных (обязательно с заголовком)
            TOKEN=$(curl -s -H "Metadata-Flavor: Google" \
              http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token \
              | jq -r .access_token)

          
            docker login -u iam -p "$TOKEN" cr.yandex

            IMAGE="${IMAGE_BASE}:${{ github.event.inputs.version }}_latest"

          
            docker pull "$IMAGE"
            docker stop store || true && docker rm store || true
            docker run -d --name store -p 80:3000 "$IMAGE"
