name: Deploy to prod

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release number (1, 2 …)"
        required: true

jobs:
  prod:
    runs-on: ubuntu-latest
    steps:
      - name: SSH → pull & run
        uses: appleboy/ssh-action@v1
        with:
          host:     ${{ secrets.SERVER_IP }}
          username: anuar
          key:      ${{ secrets.SSH_KEY }}
          script: |
            VER="${{ github.event.inputs.version }}"
            IMAGE="cr.yandex/${{ secrets.YC_REGISTRY }}/app:${VER}_latest"

            echo ">>> docker login"
            docker login -u oauth -p '${{ secrets.YC_OAUTH_TOKEN }}' cr.yandex

            echo ">>> docker pull $IMAGE"
            docker pull "$IMAGE"

            echo ">>> restart container"
            docker stop app || true && docker rm app || true
            docker run -d --name app -p 80:3000 "$IMAGE"
