with:
  host: ${{ secrets.SERVER_IP }}
  username: anuar
  key: ${{ secrets.SSH_KEY }}
  script: |
    # 1) логинимся в YCR (один раз можно оставить — лишним не будет)
    docker login -u iam -p $(curl -s http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token | jq -r .access_token) cr.yandex

    # 2) переменная с полным именем образа
    IMAGE="cr.yandex/${{ secrets.YC_REGISTRY_ID }}/app:${{ github.event.inputs.version }}_latest"

    # 3) тянем и перезапускаем контейнер
    docker pull $IMAGE
    docker stop store || true && docker rm store || true
    docker run -d --name store -p 80:3000 $IMAGE
